### PR TITLE
Public brain sync

### PR DESCRIPTION
**Pull request by LinlyBoi**
YES

### CODE REVIEW

**Review by Supermjork — CHANGES_REQUESTED** [review]
Yeet dem daily notes mf

**Review by Supermjork — COMMENTED** [review]
Acceptable state of files, should their existence be guaranteed, approval will follow.

**Review by Supermjork — APPROVED** [review]

**Comment by Supermjork** [comment]
All systems are greenlight.

**Comment by LinlyBoi** [comment]
Please do not explode

**Comment by Supermjork** [comment]
Phew.

**Pull request merged**
